In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read data
txt = "DOH COVID Data Drop_ 20210907 - 04 Case Information.csv"
data = pd.read_csv(txt) 

# Extract date from name of csv file

date = txt.split()[4]
date = list(date)
date.insert(4, '-')
date.insert(7, '-')
date = ''.join(date)

# Active Cases Per Province

In [3]:
unique_provs = data.ProvRes.unique()
unique_provs

array(['BATAAN', 'NCR', 'BULACAN', 'CAGAYAN', 'ISABELA', 'PAMPANGA',
       'TARLAC', 'ZAMBALES', 'BATANGAS', 'LAGUNA', 'QUEZON', 'RIZAL',
       'ALBAY', 'CAMARINES SUR', 'ILOILO', 'NEGROS OCCIDENTAL', 'CEBU',
       'NEGROS ORIENTAL', 'BUKIDNON', 'SOUTH COTABATO', 'BENGUET',
       'MOUNTAIN PROVINCE', 'DINAGAT ISLANDS', 'CAVITE', 'LA UNION',
       'PANGASINAN', 'NUEVA VIZCAYA', 'NUEVA ECIJA', 'CAMARINES NORTE',
       'MASBATE', 'AKLAN', 'ANTIQUE', 'CAPIZ', 'GUIMARAS', 'BOHOL',
       'LEYTE', 'SOUTHERN LEYTE', 'ZAMBOANGA DEL NORTE',
       'ZAMBOANGA DEL SUR', 'LANAO DEL NORTE', 'MISAMIS OCCIDENTAL',
       'MISAMIS ORIENTAL', 'DAVAO DEL SUR', 'DAVAO ORIENTAL',
       'COTABATO (NORTH COTABATO)', 'SULTAN KUDARAT', 'SARANGANI', 'ABRA',
       'IFUGAO', 'APAYAO', 'MAGUINDANAO', 'AGUSAN DEL SUR',
       'SURIGAO DEL SUR', 'MARINDUQUE', 'OCCIDENTAL MINDORO',
       'ORIENTAL MINDORO', nan, 'ILOCOS SUR', 'SAMAR (WESTERN SAMAR)',
       'PALAWAN', 'DAVAO DEL NORTE', 'AGUSAN DEL NORTE', 'DAVAO DE ORO',
       'ROMBLON', 'ILOCOS NORTE', 'QUIRINO', 'AURORA', 'LANAO DEL SUR',
       'DAVAO OCCIDENTAL', 'SORSOGON', 'NORTHERN SAMAR', 'KALINGA',
       'ZAMBOANGA SIBUGAY', 'SURIGAO DEL NORTE', 'BATANES', 'CATANDUANES',
       'SIQUIJOR', 'EASTERN SAMAR', 'BILIRAN',
       'CITY OF ISABELA (NOT A PROVINCE)', 'CAMIGUIN', 'SULU',
       'TAWI-TAWI', 'COTABATO CITY (NOT A PROVINCE)', 'BASILAN'],
      dtype=object)

In [4]:
needed_data = pd.DataFrame(data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")]["ProvRes"])[1:]

# Remove NCR
needed_data = needed_data[needed_data.ProvRes != 'NCR'] 

# Remove nan
needed_data.dropna(inplace=True)

# Count active cases per province
active_cases = pd.DataFrame(needed_data.value_counts(), columns=["Active"])

# Makes province into a column
active_cases["Province"] = [active_cases.index.tolist()[i][0] for i in range(0, len(active_cases))]

# Re-index
active_cases.index = np.arange(0, len(active_cases))



def proper_name(string):
    if string == "COTABATO (NORTH COTABATO)":
        string = "Cotabato"
        
    if string == "SAMAR (WESTERN SAMAR)":
        string = "Samar"
        
    if string == "CITY OF ISABELA (NOT A PROVINCE)":
        string = "City of Isabela"
        
    if string == "COTABATO CITY (NOT A PROVINCE)":
        string = "Cotabato City"
        
    if string == "DAVAO DE ORO":
        string = "Compostela Valley"
        
    string = string.lower()
    ls_string = string.split()
    
    new_string = []
    for word in ls_string:
        if word == "del":
            new_string.append('del')
            
        elif word == "de":
            new_string.append('de')
            
        elif word == "of":
            new_string.append('of')
            
        else:
            new_string.append(word.title())
        
    return ' '.join(new_string)



# Correct names
active_cases["Province"] = active_cases["Province"].apply(proper_name)

# Metro Manila districts

In [5]:
district1_data = data[data['CityMunRes'] == 'CITY OF MANILA']
first_district_MM = len(district1_data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")])


district2_data = data[(data['CityMunRes'] == 'CITY OF MANDALUYONG') | (data['CityMunRes'] == 'CITY OF MARIKINA') | (data['CityMunRes'] == 'CITY OF PASIG') | (data['CityMunRes'] == 'QUEZON CITY') | (data['CityMunRes'] == 'CITY OF SAN JUAN')]
second_district_MM = len(district2_data[(district2_data.RemovalType != "RECOVERED") & (district2_data.RemovalType != "DIED")])


district3_data = data[(data['CityMunRes'] == 'CITY OF MALABON') | (data['CityMunRes'] == 'CALOOCAN CITY') | (data['CityMunRes'] == 'CITY OF NAVOTAS')| (data['CityMunRes'] == 'CITY OF VALENZUELA') ]
third_district_MM = len(district3_data[(district3_data.RemovalType != "RECOVERED") & (district3_data.RemovalType != "DIED")])


district4_data = data[(data['CityMunRes'] == 'PATEROS') | (data['CityMunRes'] == 'CITY OF LAS PIÑAS') | (data['CityMunRes'] == 'CITY OF MAKATI')| (data['CityMunRes'] == 'CITY OF MUNTINLUPA') | (data['CityMunRes'] == 'CITY OF PARAÑAQUE') | (data['CityMunRes'] == 'PASAY CITY') | (data['CityMunRes'] == 'TAGUIG CITY') ]
fourth_district_MM = len(district4_data[(district4_data.RemovalType != "RECOVERED") & (district4_data.RemovalType != "DIED")])


ncr_dist_names = ['NCR, City of Manila, First District', 'NCR, Second District', 'NCR, Third District', 'NCR, Fourth District']
ncr_dist_values = [first_district_MM, second_district_MM, third_district_MM, fourth_district_MM]

# Add Metro Manila districts
active_cases = active_cases.append(pd.DataFrame(np.vstack([ncr_dist_values, ncr_dist_names]).T, columns=['Active', 'Province']), ignore_index=True)

<ipython-input-5-0ae93f5dfbaa>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  first_district_MM = len(district1_data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")])

In [6]:
# Rearrange order of columns
active_cases = active_cases[["Province", "Active"]]

# Alphabetical
active_cases.sort_values("Province", ascending=True, inplace=True)

# Re-index
active_cases.index = np.arange(0, len(active_cases))

In [7]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
active_cases

                               Province Active
0                                  Abra    514
1                      Agusan del Norte   1052
2                        Agusan del Sur   1126
3                                 Aklan    496
4                                 Albay    324
5                               Antique    428
6                                Apayao    535
7                                Aurora     78
8                               Basilan     13
9                                Bataan   2636
10                              Batanes      2
11                             Batangas   5947
12                              Benguet   1806
13                              Biliran    139
14                                Bohol   1382
15                             Bukidnon    899
16                              Bulacan   7688
17                              Cagayan   3835
18                      Camarines Norte    227
19                        Camarines Sur   1035
20                             Camiguin    123
21                                Capiz    565
22                          Catanduanes    110
23                               Cavite  12392
24                                 Cebu   4862
25                      City of Isabela     20
26                    Compostela Valley    291
27                             Cotabato    772
28                        Cotabato City    254
29                     Davao Occidental    380
30                       Davao Oriental    661
31                      Davao del Norte    998
32                        Davao del Sur   4590
33                      Dinagat Islands     19
34                        Eastern Samar     98
35                             Guimaras    333
36                               Ifugao    204
37                         Ilocos Norte   1159
38                           Ilocos Sur   1390
39                               Iloilo   4279
40                              Isabela   2157
41                              Kalinga    373
42                             La Union    915
43                               Laguna   9436
44                      Lanao del Norte    663
45                        Lanao del Sur    393
46                                Leyte   1741
47                          Maguindanao    278
48                           Marinduque    294
49                              Masbate    400
50                   Misamis Occidental    520
51                     Misamis Oriental   1804
52                    Mountain Province    145
53  NCR, City of Manila, First District   4892
54                 NCR, Fourth District  16284
55                 NCR, Second District  15479
56                  NCR, Third District   8122
57                    Negros Occidental   1493
58                      Negros Oriental    384
59                       Northern Samar    304
60                          Nueva Ecija   1645
61                        Nueva Vizcaya    408
62                   Occidental Mindoro    426
63                     Oriental Mindoro    253
64                              Palawan    305
65                             Pampanga   4036
66                           Pangasinan   3801
67                               Quezon   1483
68                              Quirino    313
69                                Rizal   6161
70                              Romblon    237
71                                Samar    182
72                            Sarangani    345
73                             Siquijor     46
74                             Sorsogon    342
75                       South Cotabato   1708
76                       Southern Leyte    395
77                       Sultan Kudarat    497
78                                 Sulu     15
79                    Surigao del Norte    273
80                      Surigao del Sur    721
81                               Tarlac   1803
82                            Tawi-Tawi     19
83                             Zambales   1222
84                    Zamboanga Sibugay    243
85                  Zamboanga del Norte    283
86                    Zamboanga del Sur   1234

In [8]:
active_cases.to_csv('Data/most_cases_province.csv', index=False)

# Active Cases Per Region

In [9]:
data.RegionRes.unique()

array(['Region III: Central Luzon', 'NCR', 'Region II: Cagayan Valley',
       'Region IV-A: CALABARZON', 'Region V: Bicol Region',
       'Region VI: Western Visayas', 'Region VII: Central Visayas',
       'Region X: Northern Mindanao', 'Region XII: SOCCSKSARGEN', 'CAR',
       'CARAGA', 'Region I: Ilocos Region',
       'Region VIII: Eastern Visayas', 'Region IX: Zamboanga Peninsula',
       'Region XI: Davao Region', 'BARMM', 'Region IV-B: MIMAROPA', 'ROF',
       nan], dtype=object)

In [10]:
needed_data = pd.DataFrame(data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")]["RegionRes"])[1:]

# Count active cases per province
active_cases = pd.DataFrame(needed_data.value_counts(), columns=["Active"])

# Makes province into a column
active_cases["Region"] = [active_cases.index.tolist()[i][0] for i in range(0, len(active_cases))]

# Alphabetical
active_cases.sort_values("Region", ascending=True, inplace=True)

# Index is from 0 to len(active_cases)
active_cases.index = np.arange(0, len(active_cases))

# Change order of columns
active_cases = active_cases[["Region", "Active"]]

# Delete ROF row
active_cases.drop(4, axis=0, inplace=True)

def proper_name(string):
    if string == "BARMM":
        string = "Autonomous Region in Muslim Mindanao"
        
    if string == "NCR":
        string = "National Capital Region"
        
    if string == "CARAGA":
        string = "Region XIII"
    
    if string == "CAR":
        string = "Cordillera Administrative Region"
        
    return string

def remove_region_name(string):
    if "Region" in string:
        list_text = list(string)
        index_colon = list_text.index(":")
        return ''.join(list_text[:index_colon])
    
    else:
        return string
    
# Correct names
active_cases["Region"] = active_cases["Region"].apply(remove_region_name)
active_cases["Region"] = active_cases["Region"].apply(proper_name)

active_cases = active_cases[["Region", "Active"]]
active_cases

                                  Region  Active
0   Autonomous Region in Muslim Mindanao     975
1       Cordillera Administrative Region    3580
2                            Region XIII    3191
3                National Capital Region   44972
5                               Region I    7265
6                              Region II    6715
7                             Region III   19109
8                            Region IV-A   35420
9                            Region IV-B    1515
10                             Region IX    1780
11                              Region V    2466
12                             Region VI    7594
13                            Region VII    6674
14                           Region VIII    2859
15                              Region X    4009
16                             Region XI    6920
17                            Region XII    3322

In [11]:
active_cases.to_csv('Data/most_cases_region.csv', index=False)