In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read data
txt = "DOH COVID Data Drop_ 20210909 - 04 Case Information.csv"
data = pd.read_csv(txt) 

# Extract date from name of csv file

date = txt.split()[4]
date = list(date)
date.insert(4, '-')
date.insert(7, '-')
date = ''.join(date)

# Active Cases Per Province

In [3]:
unique_provs = data.ProvRes.unique()
unique_provs

array([nan, 'CAGAYAN', 'BATAAN', 'BULACAN', 'CAVITE', 'LAGUNA',
       'CATANDUANES', 'ANTIQUE', 'ILOILO', 'NEGROS OCCIDENTAL', 'CEBU',
       'LANAO DEL NORTE', 'DAVAO DEL SUR', 'COTABATO (NORTH COTABATO)',
       'SOUTH COTABATO', 'NCR', 'BENGUET', 'AGUSAN DEL NORTE',
       'AGUSAN DEL SUR', 'SURIGAO DEL NORTE', 'SURIGAO DEL SUR',
       'PALAWAN', 'ILOCOS SUR', 'PANGASINAN', 'ISABELA', 'NUEVA VIZCAYA',
       'PAMPANGA', 'ZAMBALES', 'BATANGAS', 'QUEZON', 'RIZAL',
       'CAMARINES SUR', 'AKLAN', 'ZAMBOANGA DEL SUR', 'MISAMIS ORIENTAL',
       'MOUNTAIN PROVINCE', 'LANAO DEL SUR', 'DINAGAT ISLANDS',
       'ORIENTAL MINDORO', 'ILOCOS NORTE', 'LA UNION', 'QUIRINO',
       'NUEVA ECIJA', 'TARLAC', 'CAMARINES NORTE', 'SORSOGON', 'CAPIZ',
       'GUIMARAS', 'BOHOL', 'NEGROS ORIENTAL', 'LEYTE',
       'SAMAR (WESTERN SAMAR)', 'ZAMBOANGA DEL NORTE', 'BUKIDNON',
       'CAMIGUIN', 'DAVAO DEL NORTE', 'DAVAO ORIENTAL',
       'DAVAO OCCIDENTAL', 'SULTAN KUDARAT', 'SARANGANI', 'APAYAO',
       'MARINDUQUE', 'ROMBLON', 'MISAMIS OCCIDENTAL', 'DAVAO DE ORO',
       'EASTERN SAMAR', 'AURORA', 'KALINGA',
       'CITY OF ISABELA (NOT A PROVINCE)',
       'COTABATO CITY (NOT A PROVINCE)', 'ZAMBOANGA SIBUGAY', 'ABRA',
       'IFUGAO', 'MAGUINDANAO', 'SOUTHERN LEYTE', 'ALBAY', 'BASILAN',
       'SULU', 'TAWI-TAWI', 'OCCIDENTAL MINDORO', 'BATANES',
       'NORTHERN SAMAR', 'BILIRAN', 'MASBATE', 'SIQUIJOR'], dtype=object)

In [4]:
needed_data = pd.DataFrame(data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")]["ProvRes"])[1:]

# Remove NCR
needed_data = needed_data[needed_data.ProvRes != 'NCR'] 

# Remove nan
needed_data.dropna(inplace=True)

# Count active cases per province
active_cases = pd.DataFrame(needed_data.value_counts(), columns=["Active"])

# Makes province into a column
active_cases["Province"] = [active_cases.index.tolist()[i][0] for i in range(0, len(active_cases))]

# Re-index
active_cases.index = np.arange(0, len(active_cases))



def proper_name(string):
    if string == "COTABATO (NORTH COTABATO)":
        string = "Cotabato"
        
    if string == "SAMAR (WESTERN SAMAR)":
        string = "Samar"
        
    if string == "CITY OF ISABELA (NOT A PROVINCE)":
        string = "City of Isabela"
        
    if string == "COTABATO CITY (NOT A PROVINCE)":
        string = "Cotabato City"
        
    if string == "DAVAO DE ORO":
        string = "Compostela Valley"
        
    string = string.lower()
    ls_string = string.split()
    
    new_string = []
    for word in ls_string:
        if word == "del":
            new_string.append('del')
            
        elif word == "de":
            new_string.append('de')
            
        elif word == "of":
            new_string.append('of')
            
        else:
            new_string.append(word.title())
        
    return ' '.join(new_string)



# Correct names
active_cases["Province"] = active_cases["Province"].apply(proper_name)

# Metro Manila districts

In [5]:
district1_data = data[data['CityMunRes'] == 'CITY OF MANILA']
first_district_MM = len(district1_data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")])


district2_data = data[(data['CityMunRes'] == 'CITY OF MANDALUYONG') | (data['CityMunRes'] == 'CITY OF MARIKINA') | (data['CityMunRes'] == 'CITY OF PASIG') | (data['CityMunRes'] == 'QUEZON CITY') | (data['CityMunRes'] == 'CITY OF SAN JUAN')]
second_district_MM = len(district2_data[(district2_data.RemovalType != "RECOVERED") & (district2_data.RemovalType != "DIED")])


district3_data = data[(data['CityMunRes'] == 'CITY OF MALABON') | (data['CityMunRes'] == 'CALOOCAN CITY') | (data['CityMunRes'] == 'CITY OF NAVOTAS')| (data['CityMunRes'] == 'CITY OF VALENZUELA') ]
third_district_MM = len(district3_data[(district3_data.RemovalType != "RECOVERED") & (district3_data.RemovalType != "DIED")])


district4_data = data[(data['CityMunRes'] == 'PATEROS') | (data['CityMunRes'] == 'CITY OF LAS PIÑAS') | (data['CityMunRes'] == 'CITY OF MAKATI')| (data['CityMunRes'] == 'CITY OF MUNTINLUPA') | (data['CityMunRes'] == 'CITY OF PARAÑAQUE') | (data['CityMunRes'] == 'PASAY CITY') | (data['CityMunRes'] == 'TAGUIG CITY') ]
fourth_district_MM = len(district4_data[(district4_data.RemovalType != "RECOVERED") & (district4_data.RemovalType != "DIED")])


ncr_dist_names = ['NCR, City of Manila, First District', 'NCR, Second District', 'NCR, Third District', 'NCR, Fourth District']
ncr_dist_values = [first_district_MM, second_district_MM, third_district_MM, fourth_district_MM]

# Add Metro Manila districts
active_cases = active_cases.append(pd.DataFrame(np.vstack([ncr_dist_values, ncr_dist_names]).T, columns=['Active', 'Province']), ignore_index=True)

<ipython-input-5-0ae93f5dfbaa>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  first_district_MM = len(district1_data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")])

In [6]:
# Rearrange order of columns
active_cases = active_cases[["Province", "Active"]]

# Alphabetical
active_cases.sort_values("Province", ascending=True, inplace=True)

# Re-index
active_cases.index = np.arange(0, len(active_cases))

In [7]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
active_cases

                               Province Active
0                                  Abra    406
1                      Agusan del Norte   1233
2                        Agusan del Sur   1262
3                                 Aklan    418
4                                 Albay    295
5                               Antique    516
6                                Apayao    592
7                                Aurora    129
8                               Basilan     10
9                                Bataan   2537
10                              Batanes      2
11                             Batangas   6268
12                              Benguet   2331
13                              Biliran    176
14                                Bohol   1513
15                             Bukidnon   1161
16                              Bulacan   7792
17                              Cagayan   4119
18                      Camarines Norte    249
19                        Camarines Sur   1122
20                             Camiguin    117
21                                Capiz    501
22                          Catanduanes    147
23                               Cavite  12822
24                                 Cebu   4705
25                      City of Isabela     19
26                    Compostela Valley    285
27                             Cotabato    986
28                        Cotabato City    243
29                     Davao Occidental    478
30                       Davao Oriental    763
31                      Davao del Norte   1068
32                        Davao del Sur   4905
33                      Dinagat Islands     17
34                        Eastern Samar    100
35                             Guimaras    329
36                               Ifugao    257
37                         Ilocos Norte   1061
38                           Ilocos Sur   1666
39                               Iloilo   4194
40                              Isabela   2124
41                              Kalinga    471
42                             La Union    943
43                               Laguna   9543
44                      Lanao del Norte    664
45                        Lanao del Sur    372
46                                Leyte   1852
47                          Maguindanao    300
48                           Marinduque    341
49                              Masbate    382
50                   Misamis Occidental    737
51                     Misamis Oriental   1924
52                    Mountain Province    153
53  NCR, City of Manila, First District   4783
54                 NCR, Fourth District  15739
55                 NCR, Second District  15247
56                  NCR, Third District   8485
57                    Negros Occidental   1765
58                      Negros Oriental    529
59                       Northern Samar    381
60                          Nueva Ecija   1776
61                        Nueva Vizcaya    477
62                   Occidental Mindoro    432
63                     Oriental Mindoro    269
64                              Palawan    275
65                             Pampanga   4122
66                           Pangasinan   3887
67                               Quezon   1756
68                              Quirino    274
69                                Rizal   6369
70                              Romblon    251
71                                Samar    217
72                            Sarangani    377
73                             Siquijor     63
74                             Sorsogon    351
75                       South Cotabato   2140
76                       Southern Leyte    461
77                       Sultan Kudarat    563
78                                 Sulu     14
79                    Surigao del Norte    321
80                      Surigao del Sur    767
81                               Tarlac   1869
82                            Tawi-Tawi     21
83                             Zambales   1243
84                    Zamboanga Sibugay    292
85                  Zamboanga del Norte    496
86                    Zamboanga del Sur   1332

In [8]:
active_cases.to_csv('Data/most_cases_province.csv', index=False)

# Active Cases Per Region

In [9]:
data.RegionRes.unique()

array(['NCR', 'Region II: Cagayan Valley', 'Region III: Central Luzon',
       'Region IV-A: CALABARZON', 'Region V: Bicol Region',
       'Region VI: Western Visayas', 'Region VII: Central Visayas',
       'Region X: Northern Mindanao', 'Region XI: Davao Region',
       'Region XII: SOCCSKSARGEN', 'CAR', 'CARAGA',
       'Region IV-B: MIMAROPA', 'Region I: Ilocos Region',
       'Region IX: Zamboanga Peninsula', 'BARMM',
       'Region VIII: Eastern Visayas', 'ROF', nan], dtype=object)

In [10]:
needed_data = pd.DataFrame(data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")]["RegionRes"])[1:]

# Count active cases per province
active_cases = pd.DataFrame(needed_data.value_counts(), columns=["Active"])

# Makes province into a column
active_cases["Region"] = [active_cases.index.tolist()[i][0] for i in range(0, len(active_cases))]

# Alphabetical
active_cases.sort_values("Region", ascending=True, inplace=True)

# Index is from 0 to len(active_cases)
active_cases.index = np.arange(0, len(active_cases))

# Change order of columns
active_cases = active_cases[["Region", "Active"]]

# Delete ROF row
active_cases.drop(4, axis=0, inplace=True)

def proper_name(string):
    if string == "BARMM":
        string = "Autonomous Region in Muslim Mindanao"
        
    if string == "NCR":
        string = "National Capital Region"
        
    if string == "CARAGA":
        string = "Region XIII"
    
    if string == "CAR":
        string = "Cordillera Administrative Region"
        
    return string

def remove_region_name(string):
    if "Region" in string:
        list_text = list(string)
        index_colon = list_text.index(":")
        return ''.join(list_text[:index_colon])
    
    else:
        return string
    
# Correct names
active_cases["Region"] = active_cases["Region"].apply(remove_region_name)
active_cases["Region"] = active_cases["Region"].apply(proper_name)

active_cases = active_cases[["Region", "Active"]]
active_cases

                                  Region  Active
0   Autonomous Region in Muslim Mindanao     965
1       Cordillera Administrative Region    4213
2                            Region XIII    3600
3                National Capital Region   46665
5                               Region I    7557
6                              Region II    6996
7                             Region III   19469
8                            Region IV-A   36759
9                            Region IV-B    1568
10                             Region IX    2139
11                              Region V    2599
12                             Region VI    7723
13                            Region VII    6810
14                           Region VIII    3187
15                              Region X    4603
16                             Region XI    7499
17                            Region XII    4066

In [11]:
active_cases.to_csv('Data/most_cases_region.csv', index=False)