In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read data
txt = "DOH COVID Data Drop_ 20210916 - 04 Case Information.csv"
data = pd.read_csv(txt) 

# Extract date from name of csv file

date = txt.split()[4]
date = list(date)
date.insert(4, '-')
date.insert(7, '-')
date = ''.join(date)

# Active Cases Per Province

In [3]:
unique_provs = data.ProvRes.unique()
unique_provs

array([nan, 'LAGUNA', 'NCR', 'BATANGAS', 'PAMPANGA', 'NUEVA ECIJA',
       'ISABELA', 'DAVAO DEL NORTE', 'BULACAN', 'CAVITE',
       'NEGROS OCCIDENTAL', 'RIZAL', 'ALBAY', 'CEBU', 'ZAMBALES',
       'ILOCOS NORTE', 'ILOCOS SUR', 'LA UNION', 'PANGASINAN', 'CAGAYAN',
       'NUEVA VIZCAYA', 'QUIRINO', 'BATAAN', 'TARLAC', 'AURORA', 'QUEZON',
       'CAMARINES NORTE', 'CAMARINES SUR', 'ANTIQUE', 'GUIMARAS',
       'ZAMBOANGA SIBUGAY', 'DAVAO ORIENTAL', 'SOUTH COTABATO',
       'LANAO DEL SUR', 'AGUSAN DEL NORTE', 'ILOILO', 'NEGROS ORIENTAL',
       'DAVAO DEL SUR', 'IFUGAO', 'AGUSAN DEL SUR', 'SURIGAO DEL NORTE',
       'SURIGAO DEL SUR', 'ZAMBOANGA DEL SUR', 'MASBATE', 'AKLAN',
       'CAPIZ', 'BOHOL', 'LEYTE', 'SAMAR (WESTERN SAMAR)', 'BILIRAN',
       'BUKIDNON', 'MISAMIS ORIENTAL', 'DAVAO OCCIDENTAL',
       'COTABATO (NORTH COTABATO)', 'SARANGANI', 'ABRA', 'BENGUET',
       'KALINGA', 'APAYAO', 'COTABATO CITY (NOT A PROVINCE)',
       'MARINDUQUE', 'OCCIDENTAL MINDORO', 'PALAWAN', 'TAWI-TAWI',
       'SOUTHERN LEYTE', 'SULTAN KUDARAT', 'DAVAO DE ORO',
       'ORIENTAL MINDORO', 'ZAMBOANGA DEL NORTE', 'LANAO DEL NORTE',
       'ROMBLON', 'SORSOGON', 'MISAMIS OCCIDENTAL', 'MAGUINDANAO',
       'CATANDUANES', 'EASTERN SAMAR', 'NORTHERN SAMAR',
       'CITY OF ISABELA (NOT A PROVINCE)', 'CAMIGUIN',
       'MOUNTAIN PROVINCE', 'SIQUIJOR', 'BASILAN', 'SULU',
       'DINAGAT ISLANDS', 'BATANES'], dtype=object)

In [4]:
needed_data = pd.DataFrame(data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")]["ProvRes"])[1:]

# Remove NCR
needed_data = needed_data[needed_data.ProvRes != 'NCR'] 

# Remove nan
needed_data.dropna(inplace=True)

# Count active cases per province
active_cases = pd.DataFrame(needed_data.value_counts(), columns=["Active"])

# Makes province into a column
active_cases["Province"] = [active_cases.index.tolist()[i][0] for i in range(0, len(active_cases))]

# Re-index
active_cases.index = np.arange(0, len(active_cases))



def proper_name(string):
    if string == "COTABATO (NORTH COTABATO)":
        string = "Cotabato"
        
    if string == "SAMAR (WESTERN SAMAR)":
        string = "Samar"
        
    if string == "CITY OF ISABELA (NOT A PROVINCE)":
        string = "City of Isabela"
        
    if string == "COTABATO CITY (NOT A PROVINCE)":
        string = "Cotabato City"
        
    if string == "DAVAO DE ORO":
        string = "Compostela Valley"
        
    string = string.lower()
    ls_string = string.split()
    
    new_string = []
    for word in ls_string:
        if word == "del":
            new_string.append('del')
            
        elif word == "de":
            new_string.append('de')
            
        elif word == "of":
            new_string.append('of')
            
        else:
            new_string.append(word.title())
        
    return ' '.join(new_string)



# Correct names
active_cases["Province"] = active_cases["Province"].apply(proper_name)

# Metro Manila districts

In [5]:
district1_data = data[data['CityMunRes'] == 'CITY OF MANILA']
first_district_MM = len(district1_data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")])


district2_data = data[(data['CityMunRes'] == 'CITY OF MANDALUYONG') | (data['CityMunRes'] == 'CITY OF MARIKINA') | (data['CityMunRes'] == 'CITY OF PASIG') | (data['CityMunRes'] == 'QUEZON CITY') | (data['CityMunRes'] == 'CITY OF SAN JUAN')]
second_district_MM = len(district2_data[(district2_data.RemovalType != "RECOVERED") & (district2_data.RemovalType != "DIED")])


district3_data = data[(data['CityMunRes'] == 'CITY OF MALABON') | (data['CityMunRes'] == 'CALOOCAN CITY') | (data['CityMunRes'] == 'CITY OF NAVOTAS')| (data['CityMunRes'] == 'CITY OF VALENZUELA') ]
third_district_MM = len(district3_data[(district3_data.RemovalType != "RECOVERED") & (district3_data.RemovalType != "DIED")])


district4_data = data[(data['CityMunRes'] == 'PATEROS') | (data['CityMunRes'] == 'CITY OF LAS PIÑAS') | (data['CityMunRes'] == 'CITY OF MAKATI')| (data['CityMunRes'] == 'CITY OF MUNTINLUPA') | (data['CityMunRes'] == 'CITY OF PARAÑAQUE') | (data['CityMunRes'] == 'PASAY CITY') | (data['CityMunRes'] == 'TAGUIG CITY') ]
fourth_district_MM = len(district4_data[(district4_data.RemovalType != "RECOVERED") & (district4_data.RemovalType != "DIED")])


ncr_dist_names = ['NCR, City of Manila, First District', 'NCR, Second District', 'NCR, Third District', 'NCR, Fourth District']
ncr_dist_values = [first_district_MM, second_district_MM, third_district_MM, fourth_district_MM]

# Add Metro Manila districts
active_cases = active_cases.append(pd.DataFrame(np.vstack([ncr_dist_values, ncr_dist_names]).T, columns=['Active', 'Province']), ignore_index=True)

<ipython-input-5-0ae93f5dfbaa>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  first_district_MM = len(district1_data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")])

In [6]:
# Rearrange order of columns
active_cases = active_cases[["Province", "Active"]]

# Alphabetical
active_cases.sort_values("Province", ascending=True, inplace=True)

# Re-index
active_cases.index = np.arange(0, len(active_cases))

In [7]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
active_cases

                               Province Active
0                                  Abra    446
1                      Agusan del Norte   1535
2                        Agusan del Sur   1323
3                                 Aklan    316
4                                 Albay    550
5                               Antique    399
6                                Apayao    439
7                                Aurora    194
8                               Basilan     19
9                                Bataan   2093
10                             Batangas   6053
11                              Benguet   3162
12                              Biliran    208
13                                Bohol   1790
14                             Bukidnon   1624
15                              Bulacan   7613
16                              Cagayan   3889
17                      Camarines Norte    287
18                        Camarines Sur   1738
19                             Camiguin    102
20                                Capiz    638
21                          Catanduanes    157
22                               Cavite  11897
23                                 Cebu   3802
24                      City of Isabela     20
25                    Compostela Valley    445
26                             Cotabato    834
27                        Cotabato City    358
28                     Davao Occidental    213
29                       Davao Oriental    668
30                      Davao del Norte   1383
31                        Davao del Sur   5183
32                      Dinagat Islands     32
33                        Eastern Samar     90
34                             Guimaras    304
35                               Ifugao    417
36                         Ilocos Norte    870
37                           Ilocos Sur   1972
38                               Iloilo   4904
39                              Isabela   2337
40                              Kalinga    551
41                             La Union   1364
42                               Laguna   9008
43                      Lanao del Norte    675
44                        Lanao del Sur    536
45                                Leyte   2252
46                          Maguindanao    394
47                           Marinduque    180
48                              Masbate    444
49                   Misamis Occidental    879
50                     Misamis Oriental   1652
51                    Mountain Province    197
52  NCR, City of Manila, First District   4960
53                 NCR, Fourth District  16875
54                 NCR, Second District  18363
55                  NCR, Third District   8832
56                    Negros Occidental   2696
57                      Negros Oriental    810
58                       Northern Samar    387
59                          Nueva Ecija   2151
60                        Nueva Vizcaya    714
61                   Occidental Mindoro    314
62                     Oriental Mindoro    318
63                              Palawan    399
64                             Pampanga   4346
65                           Pangasinan   4335
66                               Quezon   1845
67                              Quirino    169
68                                Rizal   7290
69                              Romblon    105
70                                Samar    282
71                            Sarangani    466
72                             Siquijor     95
73                             Sorsogon    473
74                       South Cotabato   2519
75                       Southern Leyte    573
76                       Sultan Kudarat    773
77                                 Sulu     26
78                    Surigao del Norte    538
79                      Surigao del Sur   1076
80                               Tarlac   2073
81                            Tawi-Tawi     19
82                             Zambales   1376
83                    Zamboanga Sibugay    438
84                  Zamboanga del Norte    518
85                    Zamboanga del Sur   1594

In [8]:
active_cases.to_csv('Data/most_cases_province.csv', index=False)

# Active Cases Per Region

In [9]:
data.RegionRes.unique()

array(['NCR', 'Region IV-A: CALABARZON', 'ROF', nan,
       'Region III: Central Luzon', 'Region II: Cagayan Valley',
       'Region XI: Davao Region', 'Region VI: Western Visayas',
       'Region V: Bicol Region', 'Region VII: Central Visayas',
       'Region I: Ilocos Region', 'Region IX: Zamboanga Peninsula',
       'Region XII: SOCCSKSARGEN', 'BARMM', 'CARAGA', 'CAR',
       'Region VIII: Eastern Visayas', 'Region X: Northern Mindanao',
       'Region IV-B: MIMAROPA'], dtype=object)

In [10]:
needed_data = pd.DataFrame(data[(data.RemovalType != "RECOVERED") & (data.RemovalType != "DIED")]["RegionRes"])[1:]

# Count active cases per province
active_cases = pd.DataFrame(needed_data.value_counts(), columns=["Active"])

# Makes province into a column
active_cases["Region"] = [active_cases.index.tolist()[i][0] for i in range(0, len(active_cases))]

# Alphabetical
active_cases.sort_values("Region", ascending=True, inplace=True)

# Index is from 0 to len(active_cases)
active_cases.index = np.arange(0, len(active_cases))

# Change order of columns
active_cases = active_cases[["Region", "Active"]]

# Delete ROF row
active_cases.drop(4, axis=0, inplace=True)

def proper_name(string):
    if string == "BARMM":
        string = "Autonomous Region in Muslim Mindanao"
        
    if string == "NCR":
        string = "National Capital Region"
        
    if string == "CARAGA":
        string = "Region XIII"
    
    if string == "CAR":
        string = "Cordillera Administrative Region"
        
    return string

def remove_region_name(string):
    if "Region" in string:
        list_text = list(string)
        index_colon = list_text.index(":")
        return ''.join(list_text[:index_colon])
    
    else:
        return string
    
# Correct names
active_cases["Region"] = active_cases["Region"].apply(remove_region_name)
active_cases["Region"] = active_cases["Region"].apply(proper_name)

active_cases = active_cases[["Region", "Active"]]
active_cases

                                  Region  Active
0   Autonomous Region in Muslim Mindanao    1364
1       Cordillera Administrative Region    5216
2                            Region XIII    4504
3                National Capital Region   50074
5                               Region I    8541
6                              Region II    7109
7                             Region III   19847
8                            Region IV-A   36093
9                            Region IV-B    1316
10                             Region IX    2570
11                              Region V    4022
12                             Region VI    9257
13                            Region VII    6497
14                           Region VIII    3792
15                              Region X    4932
16                             Region XI    7892
17                            Region XII    4592

In [11]:
active_cases.to_csv('Data/most_cases_region.csv', index=False)